### ISSUE TITLE
Channel Breakout Positions Limit

### ISSUE THREAD

**Issue by altcnews** [arms22/mexbot#6]
Hi,
Thanks for the bot, it is nice.

Btw, i am testing channel breakout strategy with 1 differential price and how to set limit of maximum order placed is only one at one price? Seems that i got many orders stack at the same price.

Thank you.

**Comment by arms22** [comment]
Sorry, the function to order only one price is not implemented.

**Comment by altcnews** [comment]
It's ok.
Thank you.
